/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A Node-facing wrapper around one real core open handle. The core handle
 * owns the cursor and access mode; this layer only performs Node's
 * offset/length/position slicing and returns the requested buffer/result
 * shapes.
 */
export declare class FileHandle {
  get fd(): number | null
  read(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsReadResult>
  write(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsWriteResult>
  stat(): Promise<JsStats>
  truncate(length?: number | undefined | null): Promise<void>
  sync(): Promise<void>
  datasync(): Promise<void>
  close(): Promise<void>
}

export declare class Filesystem {
  static memory(): Filesystem
  static sqlite(path: string): Promise<Filesystem>
  static pglite(connectionString: string): Promise<Filesystem>
  static r2(options: JsR2Options): Promise<Filesystem>
  /** Upstream exposes resolved capabilities as a readonly property. */
  get capabilities(): JsCapabilities
  /** Compatibility alias for callers of the earlier Rust binding method. */
  getCapabilities(): JsCapabilities
  /**
   * Release the chunked metadata writer lease immediately. Legacy
   * snapshot factories have no lease and therefore resolve successfully.
   */
  shutdown(): Promise<void>
  stat(path: string): Promise<JsStats>
  lstat(path: string): Promise<JsStats>
  statfs(path: string): Promise<JsStatsFs>
  readdir(path: string, options?: JsReaddirOptions | undefined | null): Promise<Array<JsDirEntry>>
  get mountx(): JsMountx
  open(path: string, flags?: string | number | undefined | null, mode?: number | undefined | null): Promise<FileHandle>
  readFile(path: string): Promise<Uint8Array>
  writeFile(path: string, data: string | Uint8Array): Promise<void>
  /**
   * Return the first path created by a recursive mkdir, or `undefined` when
   * the directory already existed or the call was non-recursive.
   */
  mkdir(path: string, options?: boolean | JsMkdirOptions | undefined | null): Promise<string | undefined>
  rmdir(path: string): Promise<void>
  unlink(path: string): Promise<void>
  rename(oldPath: string, newPath: string): Promise<void>
  link(existingPath: string, newPath: string): Promise<void>
  symlink(target: string, path: string, type?: string | undefined | null): Promise<void>
  readlink(path: string): Promise<string>
  chmod(path: string, mode: number): Promise<void>
  chown(path: string, uid: number, gid: number): Promise<void>
  lchown(path: string, uid: number, gid: number): Promise<void>
  truncate(path: string, length?: number | undefined | null): Promise<void>
  /**
   * Match mountx's public TimeLike number form: seconds since epoch. Date
   * values are converted by `postlude.cjs` before reaching this native
   * method; the core contract stores whole milliseconds.
   */
  utimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  lutimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsDirEntry {
  get name(): string
  get parentPath(): string
  get fileType(): string
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsMountx {
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsStats {
  get dev(): number
  get ino(): number
  get mode(): number
  get nlink(): number
  get uid(): number
  get gid(): number
  get rdev(): number
  get size(): number
  get blksize(): number
  get blocks(): number
  get atimeMs(): number
  get mtimeMs(): number
  get ctimeMs(): number
  get birthtimeMs(): number
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsStatsFs {
  get type(): number
  get bsize(): number
  get blocks(): number
  get bfree(): number
  get bavail(): number
  get files(): number
  get ffree(): number
  get filesystemType(): number
  get blockSize(): number
  get blocksFree(): number
  get blocksAvailable(): number
  get filesFree(): number
}

/**
 * Construct a filesystem over independently selected metadata and immutable
 * block providers. The returned driver's `shutdown()` releases its writer
 * lease; callers should invoke it when the driver is no longer in use.
 */
export declare function createChunkedDriver(options: JsChunkedOptions): Promise<Filesystem>

export interface JsCapabilities {
  handles: boolean
  hardlinks: boolean
  symlinks: boolean
  permissions: boolean
  times: boolean
  truncate: boolean
  atomicRename: boolean
  caseSensitive: boolean
  statfs: boolean
  readOnly: boolean
  durableWrites: boolean
  mknod: boolean
  extensions: ReadonlyArray<string>
}

export interface JsChunkedOptions {
  metadata: JsChunkedStoreOptions
  blocks: JsChunkedStoreOptions
  chunkSize: number
  owner?: string
  ttlMs?: number
  uid?: number
  gid?: number
  umask?: number
  rootMode?: number
}

/**
 * One independently configured provider used by `createChunkedDriver`.
 * `kind` is intentionally a closed string set validated by Rust; an unknown
 * backend never falls back to an in-memory store.
 */
export interface JsChunkedStoreOptions {
  kind: string
  uri?: string
  key?: string
  durable?: boolean
  endpoint?: string
  bucket?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface JsMkdirOptions {
  recursive?: boolean
  mode?: number
}

export interface JsR2Options {
  endpoint: string
  bucket: string
  accessKeyId: string
  secretAccessKey: string
  stateKey?: string
}

export interface JsReaddirOptions {
  withFileTypes?: boolean
}

export interface JsReadResult {
  bytesRead: number
  buffer: Uint8Array
}

export interface JsWriteResult {
  bytesWritten: number
  buffer: Uint8Array
}
