/// <reference lib="esnext.disposable" />
/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A Node-facing wrapper around one real core open handle. The core handle
 * owns the cursor and access mode; this layer only performs Node's
 * offset/length/position slicing and returns the requested buffer/result
 * shapes.
 */
export declare class FileHandle {
  get fd(): number | null
  read(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsReadResult>
  write(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsWriteResult>
  stat(): Promise<JsStats>
  truncate(length?: number | undefined | null): Promise<void>
  sync(): Promise<void>
  datasync(): Promise<void>
  close(): Promise<void>
}

export declare class Filesystem {
  static memory(): Filesystem
  static sqlite(path: string): Promise<Filesystem>
  static pglite(connectionString: string): Promise<Filesystem>
  static r2(options: JsR2Options): Promise<Filesystem>
  /** Upstream exposes resolved capabilities as a readonly property. */
  get capabilities(): JsCapabilities
  /** Compatibility alias for callers of the earlier Rust binding method. */
  getCapabilities(): JsCapabilities
  /**
   * Release the chunked metadata writer lease immediately. Legacy
   * snapshot factories have no lease and therefore resolve successfully.
   */
  shutdown(): Promise<void>
  stat(path: string): Promise<JsStats>
  lstat(path: string): Promise<JsStats>
  statfs(path: string): Promise<JsStatsFs>
  readdir(path: string, options?: JsReaddirOptions | undefined | null): Promise<Array<JsDirEntry>>
  get mountx(): JsMountx
  open(path: string, flags?: string | number | undefined | null, mode?: number | undefined | null): Promise<FileHandle>
  readFile(path: string): Promise<Uint8Array>
  writeFile(path: string, data: string | Uint8Array): Promise<void>
  /**
   * Return the first path created by a recursive mkdir, or `undefined` when
   * the directory already existed or the call was non-recursive.
   */
  mkdir(path: string, options?: boolean | JsMkdirOptions | undefined | null): Promise<string | undefined>
  rmdir(path: string): Promise<void>
  unlink(path: string): Promise<void>
  rename(oldPath: string, newPath: string): Promise<void>
  link(existingPath: string, newPath: string): Promise<void>
  symlink(target: string, path: string, type?: string | undefined | null): Promise<void>
  readlink(path: string): Promise<string>
  chmod(path: string, mode: number): Promise<void>
  chown(path: string, uid: number, gid: number): Promise<void>
  lchown(path: string, uid: number, gid: number): Promise<void>
  truncate(path: string, length?: number | undefined | null): Promise<void>
  /**
   * Match mountx's public TimeLike number form: seconds since epoch. Date
   * values are converted by `postlude.cjs` before reaching this native
   * method; the core contract stores whole milliseconds.
   */
  utimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  lutimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsDirEntry {
  get name(): string
  get parentPath(): string
  get fileType(): string
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsMountx {
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsStats {
  get dev(): number
  get ino(): number
  get mode(): number
  get nlink(): number
  get uid(): number
  get gid(): number
  get rdev(): number
  get size(): number
  get blksize(): number
  get blocks(): number
  get atimeMs(): number
  get mtimeMs(): number
  get ctimeMs(): number
  get birthtimeMs(): number
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsStatsFs {
  get type(): number
  get bsize(): number
  get blocks(): number
  get bfree(): number
  get bavail(): number
  get files(): number
  get ffree(): number
  get filesystemType(): number
  get blockSize(): number
  get blocksFree(): number
  get blocksAvailable(): number
  get filesFree(): number
}

export declare class Mounted {
  get transport(): string
  get mountpoint(): string
  get source(): string | null
  get active(): boolean
  unmount(): Promise<void>
}

export declare class NfsServer {
  get host(): string
  get port(): number
  listen(): Promise<NfsServer>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare class P9Connection {
  get session(): P9Session
  get id(): number
  get peer(): string | null
  get isClosed(): boolean
  close(): Promise<void>
  waitClosed(): Promise<void>
  readonly closed: Promise<void>
}

export declare class P9Server {
  get host(): string
  get path(): string | null
  get port(): number
  get connections(): number
  address(): string | null
  clients(): Array<P9Connection>
  listen(): Promise<P9Server>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare class P9Session {
  get msize(): number | null
  get version(): string | null
  get generation(): number
  get destroyed(): boolean
  get inflight(): number
  get stats(): P9SessionStats
}

/**
 * Native equivalent of mountx's PathLock.  N-API callbacks are intentionally
 * limited to `() => Promise<void>`; arbitrary JS driver callbacks are not a
 * supported boundary for this crate.
 */
export declare class PathLock {
  constructor()
  read<T>(callback: () => T | Promise<T>): Promise<T>
  write<T>(callback: () => T | Promise<T>): Promise<T>
}

export declare class S3Server {
  get host(): string
  get port(): number
  get url(): string
  get buckets(): Array<string>
  listen(): Promise<S3Server>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare class WebdavServer {
  get host(): string
  get port(): number
  get url(): string
  get connections(): number
  listen(): Promise<WebdavServer>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare function basename(path: string): string

export declare function createChunkedDriver(options: JsChunkedOptions): Promise<Filesystem>

/**
 * Construct the N-API memory driver with the same identity and mode defaults
 * as mountx's TypeScript memory driver. `Env` is used only to read Node's
 * optional process identity helpers; the filesystem itself is entirely Rust.
 */
export declare function createMemoryDriver(options?: JsMemoryOptions | undefined | null): Filesystem

export declare function createNfsServer(driver: Filesystem, options?: NfsServerOptions | undefined | null): NfsServer

/**
 * Create the rooted host-filesystem driver used by the upstream
 * `createNodeFsDriver` API. Construction is synchronous; host I/O remains
 * asynchronous inside the Rust driver and the root is resolved lexically.
 */
export declare function createNodeFsDriver(root: string, options?: JsNodeFsOptions | undefined | null): Filesystem

export declare function createP9Server(driver: Filesystem, options?: P9ServerOptions | undefined | null): P9Server

export declare function createS3Server(source: Filesystem | { buckets: Record<string, Filesystem> }, options?: S3ServerOptions | undefined | null): S3Server

/**
 * Create a filesystem over an unstorage-compatible JavaScript store.
 *
 * The callback names and arguments match the unstorage `Storage` surface;
 * each callback may return its value directly or a Promise.  The Rust KV
 * driver remains responsible for path mapping, directory discovery, handle
 * buffering, metadata overlays, read-only checks, and flush/close behavior.
 */
export declare function createUnstorageDriver(store: object, options?: JsUnstorageOptions | undefined | null): Filesystem

export declare function createWebdavServer(driver: Filesystem, options?: WebdavServerOptions | undefined | null): WebdavServer

export declare function dirname(path: string): string

export declare function errnoCodes(): JsErrnoCodes

export declare function errnoOf(error: unknown): number

export declare function fileTypeMode(mode: number): number

export declare function fsError(code: string, options?: FsErrorOptions | undefined): FsError

export declare function isFsError(error: unknown, code?: string | undefined | null): error is FsError

export declare function isNormalizedPath(path: string): boolean

export declare function isPathInside(path: string, parent: string): boolean

export declare function isSpecialMode(mode: number): boolean

/**
 * The public TypeScript API is variadic; the postlude turns this native
 * array bridge into `joinPath(...parts)` without pretending N-API received a
 * JavaScript callback or variadic argument list directly.
 */
export declare function joinPathParts(parts: Array<string>): string

export interface JsAutoMountOptions {
  transport?: string
  readOnly?: boolean
  unmountTimeoutMs?: number
  /**
   * Apply hard mounts and same-host locking when the selected transport is
   * NFS. This does not enable WAL or distributed SQLite locking.
   */
  nfsSqliteSingleHost?: boolean
}

export interface JsAutoProbe {
  platform: string
  chosen?: string
  preference: Array<string>
  fuse: JsTransportProbe
  '9p': JsTransportProbe
  nfs: JsTransportProbe
  reason?: string
}

export interface JsCapabilities {
  handles: boolean
  hardlinks: boolean
  symlinks: boolean
  permissions: boolean
  times: boolean
  truncate: boolean
  atomicRename: boolean
  caseSensitive: boolean
  statfs: boolean
  readOnly: boolean
  durableWrites: boolean
  mknod: boolean
  extensions: ReadonlyArray<string>
}

export interface JsChunkedOptions {
  metadata: JsChunkedStoreOptions
  blocks: JsChunkedStoreOptions
  chunkSize: number
  owner?: string
  ttlMs?: number
  uid?: number
  gid?: number
  umask?: number
  rootMode?: number
}

/**
 * One independently configured provider used by `createChunkedDriver`.
 * `kind` is intentionally a closed string set validated by Rust; an unknown
 * backend never falls back to an in-memory store.
 */
export interface JsChunkedStoreOptions {
  kind: string
  uri?: string
  key?: string
  durable?: boolean
  endpoint?: string
  bucket?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface JsErrnoCodes {
  EPERM: number
  ENOENT: number
  EINTR: number
  EIO: number
  ENXIO: number
  EBADF: number
  EAGAIN: number
  ENOMEM: number
  EACCES: number
  EBUSY: number
  EEXIST: number
  EXDEV: number
  ENODEV: number
  ENOTDIR: number
  EISDIR: number
  EINVAL: number
  ENFILE: number
  EMFILE: number
  EFBIG: number
  ENOSPC: number
  ESPIPE: number
  EROFS: number
  EMLINK: number
  ERANGE: number
  ENAMETOOLONG: number
  ENOSYS: number
  ENOTEMPTY: number
  ELOOP: number
  ENODATA: number
  EPROTO: number
  EOVERFLOW: number
  ENOTSUP: number
  ESTALE: number
  EDQUOT: number
}

export interface JsMemoryOptions {
  uid?: number
  gid?: number
  umask?: number
  rootMode?: number
}

export interface JsMkdirOptions {
  recursive?: boolean
  mode?: number
}

export interface JsMountFailure {
  transport?: string
  message: string
}

export interface JsNodeFsOptions {
  readOnly?: boolean
}

export interface JsR2Options {
  endpoint: string
  bucket: string
  accessKeyId: string
  secretAccessKey: string
  stateKey?: string
}

export interface JsReaddirOptions {
  withFileTypes?: boolean
}

export interface JsReadResult {
  bytesRead: number
  buffer: Uint8Array
}

export interface JsResolvedPath {
  path: string
  segments: Array<string>
}

export interface JsTransportProbe {
  usable: boolean
  reason?: string
}

export interface JsUnstorageOptions {
  uid?: number
  gid?: number
  fileMode?: number
  dirMode?: number
  readOnly?: boolean
}

export interface JsWriteResult {
  bytesWritten: number
  buffer: Uint8Array
}

/**
 * Return facade-visible live mounts. The result contains shared lifecycle
 * handles; callers still own explicit `unmount()` responsibility.
 */
export declare function liveMounts(): Promise<Array<Mounted>>

/**
 * Mount a filesystem through the named transport or the automatic facade.
 * The Rust transport remains authoritative for platform prerequisites; this
 * function never silently falls back after a named transport fails.
 */
export declare function mount(driver: Filesystem, mountpoint: string, options?: JsAutoMountOptions | undefined | null): Promise<Mounted>

export interface NfsServerOptions {
  port?: number
  host?: string
  allowRemote?: boolean
  maxRecord?: number
  maxInFlight?: number
  useDriverIno?: boolean
  verifier?: Uint8Array
  rtmax?: number
  wtmax?: number
  dtpref?: number
  snapshotCache?: number
  claimOwnership?: boolean
}

export declare function normalizePath(path: string): string

export interface P9ServerOptions {
  port?: number
  host?: string
  path?: string
  allowRemote?: boolean
  socketMode?: number
  allowSharedDirectory?: boolean
  maxFrame?: number
  maxInFlight?: number
  msize?: number
  useDriverIno?: boolean
  readOnly?: boolean
  claimOwnership?: boolean
}

export interface P9SessionStats {
  requests: number
  replies: number
  errors: number
  dropped: number
  flushed: number
  messages: Record<string, number>
}

/**
 * Probe host facts without attempting a mount. This is safe and rootless on
 * macOS and Linux; it reports the exact automatic preference and reasons.
 */
export declare function probeTransports(): Promise<JsAutoProbe>

export declare function rangeError(name: string, expected: string, value: number): RangeError

export declare function resolvePath(path: string): JsResolvedPath

export declare const S_IFBLK: number

export declare const S_IFCHR: number

export declare const S_IFDIR: number

export declare const S_IFIFO: number

export declare const S_IFLNK: number

export declare const S_IFMT: number

export declare const S_IFREG: number

export declare const S_IFSOCK: number

export declare const S_ISGID: number

export declare const S_IXGRP: number

export interface S3Credentials {
  accessKeyId: string
  secretAccessKey: string
}

export interface S3ServerOptions {
  bucket?: string
  host?: string
  port?: number
  credentials?: S3Credentials
  region?: string
  maxBodyBytes?: number
  maxXmlBytes?: number
  readChunkBytes?: number
}

export declare function splitPath(path: string): Array<string>

/**
 * Tear down every mount visible to the automatic facade and return failures
 * individually instead of rejecting the cleanup operation.
 */
export declare function unmountAll(): Promise<Array<JsMountFailure>>

export interface WebdavCredentials {
  username: string
  password: string
}

export interface WebdavServerOptions {
  host?: string
  port?: number
  credentials?: WebdavCredentials
  realm?: string
  readChunkBytes?: number
  maxXmlBytes?: number
  maxBodyBytes?: number
  drainTimeout?: number
  debug?: boolean
}

import type { FsError, FsErrorOptions } from "./types/root.js"
export type { ErrnoCode, FsError, FsErrorOptions } from "./types/root.js"
export { ERRNO_CODES, joinPath } from "./types/root.js"
