/// <reference lib="esnext.disposable" />
/// <reference types="node" />
import type { Buffer } from "node:buffer"
/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A Node-facing wrapper around one real core open handle. The core handle
 * owns the cursor and access mode; this layer only performs Node's
 * offset/length/position slicing and returns the requested buffer/result
 * shapes.
 */
export declare class FileHandle {
  get fd(): number | null
  read(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsReadResult>
  write(buffer: Uint8Array, offset?: number | undefined | null, length?: number | undefined | null, position?: number | undefined | null): Promise<JsWriteResult>
  stat(): Promise<JsStats>
  truncate(length?: number | undefined | null): Promise<void>
  sync(): Promise<void>
  datasync(): Promise<void>
  close(): Promise<void>
}

export declare class Filesystem {
  static memory(): Filesystem
  static sqlite(path: string): Promise<Filesystem>
  static pglite(connectionString: string): Promise<Filesystem>
  static r2(options: JsR2Options): Promise<Filesystem>
  /** Upstream exposes resolved capabilities as a readonly property. */
  get capabilities(): JsCapabilities
  /** Compatibility alias for callers of the earlier Rust binding method. */
  getCapabilities(): JsCapabilities
  /**
   * Complete provider shutdown and detach this filesystem's shared driver.
   * Concurrent callers share an attempt; a failed attempt can be retried.
   * Close independent handles and servers, and finish in-flight operations,
   * before relying on shutdown to permit removal of backing files.
   */
  shutdown(): Promise<void>
  stat(path: string): Promise<JsStats>
  lstat(path: string): Promise<JsStats>
  statfs(path: string): Promise<JsStatsFs>
  readdir(path: string, options?: JsReaddirOptions | undefined | null): Promise<Array<JsDirEntry>>
  get mountx(): JsMountx
  open(path: string, flags?: string | number | undefined | null, mode?: number | undefined | null): Promise<FileHandle>
  readFile(path: string): Promise<Uint8Array>
  writeFile(path: string, data: string | Uint8Array): Promise<void>
  /**
   * Return the first path created by a recursive mkdir, or `undefined` when
   * the directory already existed or the call was non-recursive.
   */
  mkdir(path: string, options?: boolean | JsMkdirOptions | undefined | null): Promise<string | undefined>
  rmdir(path: string): Promise<void>
  unlink(path: string): Promise<void>
  rename(oldPath: string, newPath: string): Promise<void>
  link(existingPath: string, newPath: string): Promise<void>
  symlink(target: string, path: string, type?: string | undefined | null): Promise<void>
  readlink(path: string): Promise<string>
  chmod(path: string, mode: number): Promise<void>
  chown(path: string, uid: number, gid: number): Promise<void>
  lchown(path: string, uid: number, gid: number): Promise<void>
  truncate(path: string, length?: number | undefined | null): Promise<void>
  /**
   * Match mountx's public TimeLike number form: seconds since epoch. Date
   * values are converted by `postlude.cjs` before reaching this native
   * method; the core contract stores whole milliseconds.
   */
  utimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  lutimes(path: string, atime: number | Date, mtime: number | Date): Promise<void>
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsDirEntry {
  get name(): string
  get parentPath(): string
  get fileType(): string
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsMountx {
  mknod(path: string, mode: number, dev: number): Promise<void>
}

export declare class JsStats {
  get dev(): number
  get ino(): number
  get mode(): number
  get nlink(): number
  get uid(): number
  get gid(): number
  get rdev(): number
  get size(): number
  get blksize(): number
  get blocks(): number
  get atimeMs(): number
  get mtimeMs(): number
  get ctimeMs(): number
  get birthtimeMs(): number
  isFile(): boolean
  isDirectory(): boolean
  isSymbolicLink(): boolean
  isBlockDevice(): boolean
  isCharacterDevice(): boolean
  isFIFO(): boolean
  isSocket(): boolean
}

export declare class JsStatsFs {
  get type(): number
  get bsize(): number
  get blocks(): number
  get bfree(): number
  get bavail(): number
  get files(): number
  get ffree(): number
  get filesystemType(): number
  get blockSize(): number
  get blocksFree(): number
  get blocksAvailable(): number
  get filesFree(): number
}

export declare class Mounted {
  get transport(): string
  get mountpoint(): string
  get source(): string | null
  get active(): boolean
  unmount(): Promise<void>
}

export declare class NativeFuseInodeTable {
  constructor(options?: NativeFuseInodeTableOptions | undefined | null)
  get root(): NativeFuseInode
  get(nodeid: bigint): NativeFuseInode | null
  nodeids(): Array<bigint>
  at(path: string): NativeFuseInode | null
  require(nodeid: bigint): NativeFuseInode
  pathOf(nodeid: bigint): string
  requirePath(nodeid: bigint): string
  bind(path: string, statsValue: NativeFuseInodeStats): NativeFuseInode
  acquire(nodeid: bigint): NativeFuseInode
  unbind(path: string): NativeFuseInode | null
  forget(nodeid: bigint, count: bigint): boolean
  remap(from: string, to: string): void
}

export declare class NativeFuseTranscriptRecorder {
  constructor(limit?: number | undefined | null)
  get frames(): Array<NativeFuseTranscriptFrame>
  get truncated(): boolean
  get bytes(): number
  tap(direction: string, bytes: Uint8Array): void
  tapAt(direction: string, bytes: Uint8Array, now: bigint): void
  encode(): Buffer
}

export declare class NativeP9DirentPacker {
  constructor(maxSize: number)
  get size(): number
  get count(): number
  get remaining(): number
  add(value: NativeP9Dirent): boolean
  bytes(): Buffer
}

export declare class NativeP9FrameAssembler {
  constructor(limit?: number | undefined | null)
  get limit(): number
  set limit(limit: number)
  get pending(): number
  get failed(): boolean
  reset(): void
  push(chunk: Uint8Array): Array<Buffer>
}

/**
 * A JS-owned reader that keeps the input bytes alive while delegating every
 * primitive and typed operation to `mount-rs-9p`.
 */
export declare class NativeP9Reader {
  constructor(bytes: Uint8Array, offset?: number | undefined | null)
  get offset(): number
  get bytes(): Buffer
  get remaining(): number
  get atEnd(): boolean
  u8(what?: string | undefined | null): number
  u16(what?: string | undefined | null): number
  u32(what?: string | undefined | null): number
  u64(what?: string | undefined | null): bigint
  string(max?: number | undefined | null, what?: string | undefined | null): string
  qid(what?: string | undefined | null): NativeP9Qid
  blob(max?: number | undefined | null, what?: string | undefined | null): Buffer
  raw(count: number, what?: string | undefined | null): Buffer
  rest(): Buffer
  end(what?: string | undefined | null): void
  readHeader(): NativeP9Header
  readTime(what?: string | undefined | null): NativeP9Time
  readTversion(): NativeP9Tversion
  readRversion(): NativeP9Tversion
  readTauth(): NativeP9Tauth
  readRauth(): NativeP9Rauth
  readTattach(): NativeP9Tattach
  readRattach(): NativeP9Rattach
  readRlerror(): NativeP9Rlerror
  readTflush(): NativeP9Tflush
  readTwalk(): NativeP9Twalk
  readRwalk(): NativeP9Rwalk
  readTread(): NativeP9Tread
  readRread(): NativeP9Rread
  readTwrite(): NativeP9Twrite
  readRwrite(): NativeP9Rwrite
  readFidRequest(): NativeP9FidRequest
  readRstatfs(): NativeP9Rstatfs
  readTlopen(): NativeP9Tlopen
  readRlopen(): NativeP9Rlopen
  readTlcreate(): NativeP9Tlcreate
  readTsymlink(): NativeP9Tsymlink
  readQidReply(): NativeP9QidReply
  readTmknod(): NativeP9Tmknod
  readTmkdir(): NativeP9Tmkdir
  readTrename(): NativeP9Trename
  readTrenameat(): NativeP9Trenameat
  readTunlinkat(): NativeP9Tunlinkat
  readTlink(): NativeP9Tlink
  readRreadlink(): NativeP9Rreadlink
  readTgetattr(): NativeP9Tgetattr
  readRgetattr(): NativeP9Rgetattr
  readTsetattr(): NativeP9Tsetattr
  readTxattrwalk(): NativeP9Txattrwalk
  readRxattrwalk(): NativeP9Rxattrwalk
  readTxattrcreate(): NativeP9Txattrcreate
  readTreaddir(): NativeP9Treaddir
  readRreaddir(): NativeP9Rreaddir
  readDirent(): NativeP9Dirent
  readDirents(): Array<NativeP9Dirent>
  readTfsync(): NativeP9Tfsync
  readTlock(): NativeP9Tlock
  readRlock(): NativeP9Rlock
  readTgetlock(): NativeP9Tgetlock
  readRgetlock(): NativeP9Rgetlock
}

/**
 * A Rust-backed growable writer.  The postlude supplies the upstream
 * chainable return convention; the bytes and all scalar writes stay native.
 */
export declare class NativeP9Writer {
  constructor(capacity?: number | undefined | null)
  get length(): number
  u8(value: number): void
  u16(value: number): void
  u32(value: number): void
  u64(value: bigint): void
  string(value: string): void
  qid(value: NativeP9Qid): void
  blob(value: Uint8Array): void
  raw(value: Uint8Array): void
  patchU32(at: number, value: number): void
  bytes(): Buffer
  writeHeader(header: NativeP9Header): void
  writeTime(value: NativeP9Time): void
  writeTversion(value: NativeP9Tversion): void
  writeRversion(value: NativeP9Tversion): void
  writeTauth(value: NativeP9Tauth): void
  writeRauth(value: NativeP9Rauth): void
  writeTattach(value: NativeP9Tattach): void
  writeRattach(value: NativeP9Rattach): void
  writeRlerror(value: NativeP9Rlerror): void
  writeTflush(value: NativeP9Tflush): void
  writeTwalk(value: NativeP9Twalk): void
  writeRwalk(value: NativeP9Rwalk): void
  writeTread(value: NativeP9Tread): void
  writeRread(value: NativeP9Rread): void
  writeTwrite(value: NativeP9Twrite): void
  writeRwrite(value: NativeP9Rwrite): void
  writeFidRequest(value: NativeP9FidRequest): void
  writeRstatfs(value: NativeP9Rstatfs): void
  writeTlopen(value: NativeP9Tlopen): void
  writeRlopen(value: NativeP9Rlopen): void
  writeTlcreate(value: NativeP9Tlcreate): void
  writeTsymlink(value: NativeP9Tsymlink): void
  writeQidReply(value: NativeP9QidReply): void
  writeTmknod(value: NativeP9Tmknod): void
  writeTmkdir(value: NativeP9Tmkdir): void
  writeTrename(value: NativeP9Trename): void
  writeTrenameat(value: NativeP9Trenameat): void
  writeTunlinkat(value: NativeP9Tunlinkat): void
  writeTlink(value: NativeP9Tlink): void
  writeRreadlink(value: NativeP9Rreadlink): void
  writeTgetattr(value: NativeP9Tgetattr): void
  writeRgetattr(value: NativeP9Rgetattr): void
  writeTsetattr(value: NativeP9Tsetattr): void
  writeTxattrwalk(value: NativeP9Txattrwalk): void
  writeRxattrwalk(value: NativeP9Rxattrwalk): void
  writeTxattrcreate(value: NativeP9Txattrcreate): void
  writeTreaddir(value: NativeP9Treaddir): void
  writeRreaddir(value: NativeP9Rreaddir): void
  writeDirent(value: NativeP9Dirent): void
  writeTfsync(value: NativeP9Tfsync): void
  writeTlock(value: NativeP9Tlock): void
  writeRlock(value: NativeP9Rlock): void
  writeTgetlock(value: NativeP9Tgetlock): void
  writeRgetlock(value: NativeP9Rgetlock): void
}

export declare class NfsRecordAssembler {
  constructor(limit?: number | undefined | null)
  get pending(): number
  push(chunk: Uint8Array): Array<Buffer>
}

export declare class NfsServer {
  get host(): string
  get port(): number
  listen(): Promise<NfsServer>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

/**
 * An owned XDR reader.  The transport reader remains borrowed internally for
 * each operation, so no N-API object can retain a view into JavaScript memory.
 */
export declare class NfsXdrReader {
  constructor(bytes: Uint8Array, offset?: number | undefined | null)
  get bytes(): Buffer
  get offset(): number
  get remaining(): number
  get atEnd(): boolean
  u32(what?: string | undefined | null): number
  i32(what?: string | undefined | null): number
  u64(what?: string | undefined | null): bigint
  i64(what?: string | undefined | null): bigint
  bool(what?: string | undefined | null): boolean
  fixedOpaque(length: number, what?: string | undefined | null): Buffer
  varOpaque(max?: number | undefined | null, what?: string | undefined | null): Buffer
  string(max?: number | undefined | null, what?: string | undefined | null): string
  rest(): Buffer
  end(what?: string | undefined | null): void
}

/** An owned XDR writer backed by the transport crate's writer. */
export declare class NfsXdrWriter {
  constructor(capacity?: number | undefined | null)
  get length(): number
  ensure(count: number): void
  truncate(length: number): void
  u32(value: number): void
  i32(value: number): void
  u64(value: bigint): void
  i64(value: bigint): void
  bool(value: boolean): void
  fixedOpaque(value: Uint8Array, length?: number | undefined | null): void
  varOpaque(value: Uint8Array): void
  string(value: string): void
  raw(value: Uint8Array): void
  bytes(): Buffer
  view(): Buffer
  nfsWriteAcceptedReplyHeader(xid: number): void
}

export declare class P9Connection {
  get session(): P9Session
  get id(): number
  get peer(): string | null
  get isClosed(): boolean
  close(): Promise<void>
  waitClosed(): Promise<void>
  readonly closed: Promise<void>
}

export declare class P9Server {
  get host(): string
  get path(): string | null
  get port(): number
  get connections(): number
  address(): string | null
  clients(): Array<P9Connection>
  listen(): Promise<P9Server>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare class P9Session {
  get msize(): number | null
  get version(): string | null
  get generation(): number
  get destroyed(): boolean
  get inflight(): number
  get stats(): P9SessionStats
}

/**
 * Native equivalent of mountx's PathLock.  N-API callbacks are intentionally
 * limited to `() => Promise<void>`; arbitrary JS driver callbacks are not a
 * supported boundary for this crate.
 */
export declare class PathLock {
  constructor()
  read<T>(callback: () => T | Promise<T>): Promise<T>
  write<T>(callback: () => T | Promise<T>): Promise<T>
}

export declare class S3Server {
  get host(): string
  get port(): number
  get url(): string
  get buckets(): Array<string>
  listen(): Promise<S3Server>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare class WebdavServer {
  get host(): string
  get port(): number
  get url(): string
  get connections(): number
  listen(): Promise<WebdavServer>
  close(): Promise<void>
  [Symbol.asyncDispose](): Promise<void>
}

export declare function basename(path: string): string

export declare function createChunkedDriver(options: JsChunkedOptions): Promise<Filesystem>

/**
 * Construct a Rust `Filesystem` backed by a structural JavaScript
 * `FsDriver` object.  `lib.rs` owns the root N-API export; this function is
 * kept here so the adapter remains isolated from the existing native drivers.
 */
export declare function createDriver(driver: FsDriver): Filesystem

/**
 * Construct the N-API memory driver with the same identity and mode defaults
 * as mountx's TypeScript memory driver. `Env` is used only to read Node's
 * optional process identity helpers; the filesystem itself is entirely Rust.
 */
export declare function createMemoryDriver(options?: JsMemoryOptions | undefined | null): Filesystem

export declare function createNfsServer(driver: Filesystem | FsDriver, options?: NfsServerOptions | undefined | null): NfsServer

/**
 * Create the rooted host-filesystem driver used by the upstream
 * `createNodeFsDriver` API. Construction is synchronous; host I/O remains
 * asynchronous inside the Rust driver and the root is resolved lexically.
 */
export declare function createNodeFsDriver(root: string, options?: JsNodeFsOptions | undefined | null): Filesystem

export declare function createP9Server(driver: Filesystem | FsDriver, options?: P9ServerOptions | undefined | null): P9Server

export declare function createS3Server(source: Filesystem | FsDriver | { buckets: Record<string, Filesystem | FsDriver> }, options?: S3ServerOptions | undefined | null): S3Server

/**
 * Create a filesystem over an unstorage-compatible JavaScript store.
 *
 * The callback names and arguments match the unstorage `Storage` surface;
 * each callback may return its value directly or a Promise.  The Rust KV
 * driver remains responsible for path mapping, directory discovery, handle
 * buffering, metadata overlays, read-only checks, and flush/close behavior.
 */
export declare function createUnstorageDriver(store: object, options?: JsUnstorageOptions | undefined | null): Filesystem

export declare function createWebdavServer(driver: Filesystem | FsDriver, options?: WebdavServerOptions | undefined | null): WebdavServer

export declare function dirname(path: string): string

export declare function errnoCodes(): JsErrnoCodes

export declare function errnoOf(error: unknown): number

export declare function fileTypeMode(mode: number): number

export declare function fsError(code: string, options?: FsErrorOptions | undefined): FsError

export declare function fuseAttrOutSize(minor: number): number

export declare function fuseAttrSize(minor: number): number

export declare function fuseDecodeAttrOut(body: Uint8Array, context?: NativeFuseProtocolContext | undefined | null): NativeFuseAttrOut

export declare function fuseDecodeEntryOut(body: Uint8Array, context?: NativeFuseProtocolContext | undefined | null): NativeFuseEntryOut

export declare function fuseDecodeGetxattrOut(body: Uint8Array): NativeFuseGetxattrOut

export declare function fuseDecodeInHeader(bytes: Uint8Array): NativeFuseInHeader

export declare function fuseDecodeInitIn(body: Uint8Array): NativeFuseInitIn

export declare function fuseDecodeInitOut(body: Uint8Array): NativeFuseInitOut

export declare function fuseDecodeNotify(message: Uint8Array): NativeFuseNotification

export declare function fuseDecodeNotifyInvalEntry(body: Uint8Array): NativeFuseNotifyInvalEntryOut

export declare function fuseDecodeNotifyInvalInode(body: Uint8Array): NativeFuseNotifyInvalInodeOut

export declare function fuseDecodeOpenOut(body: Uint8Array, context?: NativeFuseProtocolContext | undefined | null): NativeFuseOpenOut

export declare function fuseDecodeOutHeader(bytes: Uint8Array): NativeFuseOutHeader

export declare function fuseDecodeStatfsOut(body: Uint8Array, context?: NativeFuseProtocolContext | undefined | null): NativeFuseKstatfs

export declare function fuseDecodeTranscript(bytes: Uint8Array): Array<NativeFuseTranscriptFrame>

export declare function fuseDecodeXattrNames(body: Uint8Array): Array<string>

export declare function fuseDirentAlign(size: number): number

export declare function fuseDirentPlusSize(nameByteLength: number, context?: NativeFuseProtocolContext | undefined | null): number

export declare function fuseDirentSize(nameByteLength: number): number

export declare function fuseDirentType(mode: number): number

export declare function fuseEncodeAttrOut(value: NativeFuseAttrOut, context?: NativeFuseProtocolContext | undefined | null): Buffer

export declare function fuseEncodeEntryOut(value: NativeFuseEntryOut, context?: NativeFuseProtocolContext | undefined | null): Buffer

export declare function fuseEncodeErrorReply(unique: bigint, errno: number): Buffer

export declare function fuseEncodeGetxattrOut(value: NativeFuseGetxattrOut): Buffer

export declare function fuseEncodeInHeader(value: NativeFuseInHeader): Buffer

export declare function fuseEncodeInitIn(value: NativeFuseInitIn): Buffer

export declare function fuseEncodeInitOut(value: NativeFuseInitOut, context?: NativeFuseProtocolContext | undefined | null): Buffer

export declare function fuseEncodeNotify(code: number, body: Uint8Array): Buffer

export declare function fuseEncodeNotifyInvalEntry(value: NativeFuseNotifyInvalEntryOut): Buffer

export declare function fuseEncodeNotifyInvalInode(value: NativeFuseNotifyInvalInodeOut): Buffer

export declare function fuseEncodeOpenOut(value: NativeFuseOpenOut, context?: NativeFuseProtocolContext | undefined | null): Buffer

export declare function fuseEncodeOutHeader(value: NativeFuseOutHeader): Buffer

export declare function fuseEncodeReply(unique: bigint, body?: Uint8Array): Buffer

export declare function fuseEncodeStatfsOut(value: NativeFuseKstatfs, context?: NativeFuseProtocolContext | undefined | null): Buffer

export declare function fuseEncodeTranscript(frames: Array<NativeFuseTranscriptFrame>): Buffer

export declare function fuseEncodeXattrNames(names: Array<string>): Buffer

export declare function fuseEntryOutSize(minor: number): number

export declare function fuseFuseErrno(errno: number): number

export declare function fuseInitOutSize(minor: number): number

export declare function fuseJoinInitFlags(flags: number, flags2: number): bigint

export declare function fuseKstatfsSize(minor: number): number

export declare function fuseOpcodeName(opcode: number): string

export declare function fuseReadWriteInSize(minor: number): number

export declare function fuseSplitInitFlags(flags: bigint): NativeFuseSplitInitFlags

export declare function fuseSupportedOpcodes(): Array<number>

export declare function fuseUnimplementedOpcodes(): Array<number>

export declare function isFsError(error: unknown, code?: string | undefined | null): error is FsError

export declare function isNormalizedPath(path: string): boolean

export declare function isPathInside(path: string, parent: string): boolean

export declare function isSpecialMode(mode: number): boolean

/**
 * The public TypeScript API is variadic; the postlude turns this native
 * array bridge into `joinPath(...parts)` without pretending N-API received a
 * JavaScript callback or variadic argument list directly.
 */
export declare function joinPathParts(parts: Array<string>): string

export interface JsAutoMountOptions {
  transport?: string
  readOnly?: boolean
  unmountTimeoutMs?: number
  /**
   * Apply hard mounts and same-host locking when the selected transport is
   * NFS. This does not enable WAL or distributed SQLite locking.
   */
  nfsSqliteSingleHost?: boolean
}

export interface JsAutoProbe {
  platform: string
  chosen?: string
  preference: Array<string>
  fuse: JsTransportProbe
  '9p': JsTransportProbe
  nfs: JsTransportProbe
  reason?: string
}

export interface JsCapabilities {
  handles: boolean
  hardlinks: boolean
  symlinks: boolean
  permissions: boolean
  times: boolean
  truncate: boolean
  atomicRename: boolean
  caseSensitive: boolean
  statfs: boolean
  readOnly: boolean
  durableWrites: boolean
  mknod: boolean
  extensions: ReadonlyArray<string>
}

export interface JsChunkedOptions {
  metadata: JsChunkedStoreOptions
  blocks: JsChunkedStoreOptions
  chunkSize: number
  owner?: string
  ttlMs?: number
  uid?: number
  gid?: number
  umask?: number
  rootMode?: number
}

/**
 * One independently configured provider used by `createChunkedDriver`.
 * `kind` is intentionally a closed string set validated by Rust; an unknown
 * backend never falls back to an in-memory store.
 */
export interface JsChunkedStoreOptions {
  kind: string
  uri?: string
  key?: string
  durable?: boolean
  endpoint?: string
  bucket?: string
  accessKeyId?: string
  secretAccessKey?: string
}

export interface JsErrnoCodes {
  EPERM: number
  ENOENT: number
  EINTR: number
  EIO: number
  ENXIO: number
  EBADF: number
  EAGAIN: number
  ENOMEM: number
  EACCES: number
  EBUSY: number
  EEXIST: number
  EXDEV: number
  ENODEV: number
  ENOTDIR: number
  EISDIR: number
  EINVAL: number
  ENFILE: number
  EMFILE: number
  EFBIG: number
  ENOSPC: number
  ESPIPE: number
  EROFS: number
  EMLINK: number
  ERANGE: number
  ENAMETOOLONG: number
  ENOSYS: number
  ENOTEMPTY: number
  ELOOP: number
  ENODATA: number
  EPROTO: number
  EOVERFLOW: number
  ENOTSUP: number
  ESTALE: number
  EDQUOT: number
}

export interface JsMemoryOptions {
  uid?: number
  gid?: number
  umask?: number
  rootMode?: number
}

export interface JsMkdirOptions {
  recursive?: boolean
  mode?: number
}

export interface JsMountFailure {
  transport?: string
  message: string
}

export interface JsNodeFsOptions {
  readOnly?: boolean
}

export interface JsR2Options {
  endpoint: string
  bucket: string
  accessKeyId: string
  secretAccessKey: string
  stateKey?: string
}

export interface JsReaddirOptions {
  withFileTypes?: boolean
}

export interface JsReadResult {
  bytesRead: number
  buffer: Uint8Array
}

export interface JsResolvedPath {
  path: string
  segments: Array<string>
}

export interface JsTransportProbe {
  usable: boolean
  reason?: string
}

export interface JsUnstorageOptions {
  uid?: number
  gid?: number
  fileMode?: number
  dirMode?: number
  readOnly?: boolean
}

export interface JsUtimensOptions {
  followSymlinks?: boolean
}

export interface JsWriteResult {
  bytesWritten: number
  buffer: Uint8Array
}

/**
 * Return facade-visible live mounts. The result contains shared lifecycle
 * handles; callers still own explicit `unmount()` responsibility.
 */
export declare function liveMounts(): Promise<Array<Mounted>>

/**
 * Mount a filesystem through the named transport or the automatic facade.
 * The Rust transport remains authoritative for platform prerequisites; this
 * function never silently falls back after a named transport fails.
 */
export declare function mount(driver: Filesystem | FsDriver, mountpoint: string, options?: JsAutoMountOptions | undefined | null): Promise<Mounted>

export interface NativeFuseAttr {
  ino: bigint
  size: bigint
  blocks: bigint
  atime: bigint
  mtime: bigint
  ctime: bigint
  atimensec: number
  mtimensec: number
  ctimensec: number
  mode: number
  nlink: number
  uid: number
  gid: number
  rdev: number
  blksize: number
  flags: number
}

export interface NativeFuseAttrOut {
  attrValid: bigint
  attrValidNsec: number
  attr: NativeFuseAttr
}

export interface NativeFuseEntryOut {
  nodeid: bigint
  generation: bigint
  entryValid: bigint
  attrValid: bigint
  entryValidNsec: number
  attrValidNsec: number
  attr: NativeFuseAttr
}

export interface NativeFuseGetxattrOut {
  size: number
}

export interface NativeFuseInHeader {
  len: number
  opcode: number
  unique: bigint
  nodeid: bigint
  uid: number
  gid: number
  pid: number
  totalExtlen: number
}

export interface NativeFuseInitIn {
  major: number
  minor: number
  maxReadahead: number
  flags: number
  flags2: number
}

export interface NativeFuseInitOut {
  major: number
  minor: number
  maxReadahead: number
  flags: number
  maxBackground: number
  congestionThreshold: number
  maxWrite: number
  timeGran: number
  maxPages: number
  mapAlignment: number
  flags2: number
  maxStackDepth: number
}

export interface NativeFuseInode {
  nodeid: bigint
  key?: string
  nlookup: bigint
  paths: Array<string>
}

export interface NativeFuseInodeStats {
  dev: number
  ino: number
}

export interface NativeFuseInodeTableOptions {
  useDriverIno?: boolean
}

export interface NativeFuseKstatfs {
  blocks: bigint
  bfree: bigint
  bavail: bigint
  files: bigint
  ffree: bigint
  bsize: number
  namelen: number
  frsize: number
}

export interface NativeFuseNotification {
  code: number
  body: Uint8Array
}

export interface NativeFuseNotifyInvalEntryOut {
  parent: bigint
  name: string
  flags: number
}

export interface NativeFuseNotifyInvalInodeOut {
  ino: bigint
  off: bigint
  len: bigint
}

export interface NativeFuseOpenOut {
  fh: bigint
  openFlags: number
  backingId: number
}

export interface NativeFuseOutHeader {
  len: number
  error: number
  unique: bigint
}

export interface NativeFuseProtocolContext {
  minor: number
  setxattrExt: boolean
}

export interface NativeFuseSplitInitFlags {
  flags: number
  flags2: number
}

export interface NativeFuseTranscriptFrame {
  direction: string
  timestamp: bigint
  bytes: Uint8Array
}

export declare function nativeP9DecodeMessage(bytes: Uint8Array): NativeP9Message

export interface NativeP9Dirent {
  qid: NativeP9Qid
  offset: bigint
  type: number
  name: string
}

export declare function nativeP9DirentSize(value: string): number

export declare function nativeP9EncodeMessage(type: number, tag: number, body: Uint8Array, capacity?: number | undefined | null): Buffer

export interface NativeP9FidRequest {
  fid: number
}

export interface NativeP9Header {
  size: number
  type: number
  tag: number
}

export interface NativeP9Message {
  header: NativeP9Header
  body: Uint8Array
}

export interface NativeP9Qid {
  type: number
  version: number
  path: bigint
}

export interface NativeP9QidReply {
  qid: NativeP9Qid
}

export interface NativeP9Rattach {
  qid: NativeP9Qid
}

export interface NativeP9Rauth {
  aqid: NativeP9Qid
}

export declare function nativeP9ReadDirents(bytes: Uint8Array): Array<NativeP9Dirent>

export interface NativeP9Rgetattr {
  valid: bigint
  qid: NativeP9Qid
  mode: number
  uid: number
  gid: number
  nlink: bigint
  rdev: bigint
  size: bigint
  blksize: bigint
  blocks: bigint
  atime: NativeP9Time
  mtime: NativeP9Time
  ctime: NativeP9Time
  btime: NativeP9Time
  gen: bigint
  dataVersion: bigint
}

export interface NativeP9Rgetlock {
  type: number
  start: bigint
  length: bigint
  procId: number
  clientId: string
}

export interface NativeP9Rlerror {
  ecode: number
}

export interface NativeP9Rlock {
  status: number
}

export interface NativeP9Rlopen {
  qid: NativeP9Qid
  iounit: number
}

export interface NativeP9Rread {
  data: Uint8Array
}

export interface NativeP9Rreaddir {
  data: Uint8Array
}

export interface NativeP9Rreadlink {
  target: string
}

export interface NativeP9Rstatfs {
  type: number
  bsize: number
  blocks: bigint
  bfree: bigint
  bavail: bigint
  files: bigint
  ffree: bigint
  fsid: bigint
  namelen: number
}

export interface NativeP9Rwalk {
  wqids: Array<NativeP9Qid>
}

export interface NativeP9Rwrite {
  count: number
}

export interface NativeP9Rxattrwalk {
  size: bigint
}

export declare function nativeP9StringByteLength(value: string): number

export interface NativeP9Tattach {
  fid: number
  afid: number
  uname: string
  aname: string
  nUname: number
}

export interface NativeP9Tauth {
  afid: number
  uname: string
  aname: string
  nUname: number
}

export interface NativeP9Tflush {
  oldtag: number
}

export interface NativeP9Tfsync {
  fid: number
  datasync: number
}

export interface NativeP9Tgetattr {
  fid: number
  requestMask: bigint
}

export interface NativeP9Tgetlock {
  fid: number
  type: number
  start: bigint
  length: bigint
  procId: number
  clientId: string
}

export interface NativeP9Time {
  sec: bigint
  nsec: bigint
}

export interface NativeP9Tlcreate {
  fid: number
  name: string
  flags: number
  mode: number
  gid: number
}

export interface NativeP9Tlink {
  dfid: number
  fid: number
  name: string
}

export interface NativeP9Tlock {
  fid: number
  type: number
  flags: number
  start: bigint
  length: bigint
  procId: number
  clientId: string
}

export interface NativeP9Tlopen {
  fid: number
  flags: number
}

export interface NativeP9Tmkdir {
  dfid: number
  name: string
  mode: number
  gid: number
}

export interface NativeP9Tmknod {
  dfid: number
  name: string
  mode: number
  major: number
  minor: number
  gid: number
}

export interface NativeP9Tread {
  fid: number
  offset: bigint
  count: number
}

export interface NativeP9Treaddir {
  fid: number
  offset: bigint
  count: number
}

export interface NativeP9Trename {
  fid: number
  dfid: number
  name: string
}

export interface NativeP9Trenameat {
  olddirfid: number
  oldname: string
  newdirfid: number
  newname: string
}

export interface NativeP9Tsetattr {
  fid: number
  valid: number
  mode: number
  uid: number
  gid: number
  size: bigint
  atime: NativeP9Time
  mtime: NativeP9Time
}

export interface NativeP9Tsymlink {
  dfid: number
  name: string
  symtgt: string
  gid: number
}

export interface NativeP9Tunlinkat {
  dirfid: number
  name: string
  flags: number
}

export interface NativeP9Tversion {
  msize: number
  version: string
}

export interface NativeP9Twalk {
  fid: number
  newfid: number
  wnames: Array<string>
}

export interface NativeP9Twrite {
  fid: number
  offset: bigint
  data: Uint8Array
}

export interface NativeP9Txattrcreate {
  fid: number
  name: string
  attrSize: bigint
  flags: number
}

export interface NativeP9Txattrwalk {
  fid: number
  newfid: number
  name: string
}

export declare function nfsAuthNull(): NfsOpaqueAuth

export declare function nfsAuthSys(uid?: number | undefined | null, gid?: number | undefined | null, machineName?: string | undefined | null): NfsOpaqueAuth

export interface NfsAuthSysParams {
  stamp: number
  machineName: string
  uid: number
  gid: number
  gids: Array<number>
}

export declare function nfsCopyBytes(bytes: Uint8Array, start?: number | undefined | null, end?: number | undefined | null): Buffer

export declare function nfsCredentialsOf(credential: NfsOpaqueAuth): NfsRpcCredentials

export declare function nfsDecodeAuthSys(body: Uint8Array): NfsAuthSysParams

export declare function nfsDecodeCall(bytes: Uint8Array): NfsDecodedCall

export interface NfsDecodedCall {
  call: NfsRpcCall
  argsBytes: Uint8Array
  argsOffset: number
}

export interface NfsDecodedReply {
  reply: NfsRpcReply
  resultsBytes: Uint8Array
  resultsOffset: number
}

export declare function nfsDecodeReply(bytes: Uint8Array): NfsDecodedReply

export declare function nfsEncodeAcceptedReply(xid: number, results?: Buffer | undefined | null): Buffer

export declare function nfsEncodeAcceptError(xid: number, acceptStat: number, mismatch?: NfsRpcMismatch | undefined | null): Buffer

export declare function nfsEncodeAuthError(xid: number, authStat: number): Buffer

export declare function nfsEncodeAuthSys(params: NfsAuthSysParams): Buffer

export declare function nfsEncodeCall(options: NfsRpcCallOptions): Buffer

export declare function nfsEncodeRpcMismatch(xid: number, low?: number | undefined | null, high?: number | undefined | null): Buffer

export declare function nfsFrameFragments(message: Uint8Array, size: number): Buffer

export declare function nfsFrameRecord(message: Uint8Array): Buffer

export interface NfsOpaqueAuth {
  flavor: number
  body: Uint8Array
}

export declare function nfsRecordMark(length: number): Buffer

export interface NfsRpcCall {
  xid: number
  rpcVersion: number
  program: number
  version: number
  procedure: number
  cred: NfsOpaqueAuth
  verf: NfsOpaqueAuth
}

export interface NfsRpcCallOptions {
  xid: number
  program: number
  version: number
  procedure: number
  cred?: NfsOpaqueAuth
  verf?: NfsOpaqueAuth
  args?: Uint8Array
}

export declare function nfsRpcConstants(): NfsRpcConstants

export interface NfsRpcConstants {
  RPC_VERSION: number
  RPC_CALL: number
  RPC_REPLY: number
  MSG_ACCEPTED: number
  MSG_DENIED: number
  RPC_SUCCESS: number
  RPC_PROG_UNAVAIL: number
  RPC_PROG_MISMATCH: number
  RPC_PROC_UNAVAIL: number
  RPC_GARBAGE_ARGS: number
  RPC_SYSTEM_ERR: number
  RPC_MISMATCH: number
  RPC_AUTH_ERROR: number
  AUTH_OK: number
  AUTH_BADCRED: number
  AUTH_REJECTEDCRED: number
  AUTH_BADVERF: number
  AUTH_REJECTEDVERF: number
  AUTH_TOOWEAK: number
  AUTH_INVALIDRESP: number
  AUTH_FAILED: number
  AUTH_NONE: number
  AUTH_SYS: number
  AUTH_SHORT: number
  RPC_MAX_AUTH_BYTES: number
  RM_LAST_FRAGMENT: number
  RM_LENGTH_MASK: number
  ACCEPTED_REPLY_HEADER_SIZE: number
  DEFAULT_RECORD_LIMIT: number
}

export interface NfsRpcCredentials {
  flavor: number
  uid?: number
  gid?: number
  gids: Array<number>
}

export interface NfsRpcMismatch {
  low: number
  high: number
}

export interface NfsRpcReply {
  xid: number
  replyStat: number
  acceptStat?: number
  rejectStat?: number
  authStat?: number
  low?: number
  high?: number
  verf?: NfsOpaqueAuth
}

export interface NfsServerOptions {
  port?: number
  host?: string
  allowRemote?: boolean
  maxRecord?: number
  maxInFlight?: number
  useDriverIno?: boolean
  verifier?: Uint8Array
  rtmax?: number
  wtmax?: number
  dtpref?: number
  snapshotCache?: number
  claimOwnership?: boolean
  onTransportError?: (error: unknown, peer: string | undefined) => void
}

export declare function nfsStringByteLength(value: string): number

export declare function nfsXdrAlign(length: number): number

export declare function nfsXdrPad(length: number): number

export declare function normalizePath(path: string): string

export interface P9ServerOptions {
  port?: number
  host?: string
  path?: string
  allowRemote?: boolean
  socketMode?: number
  allowSharedDirectory?: boolean
  maxFrame?: number
  maxInFlight?: number
  msize?: number
  useDriverIno?: boolean
  readOnly?: boolean
  claimOwnership?: boolean
  onTransportError?: (error: unknown, peer: string | undefined) => void
}

export interface P9SessionStats {
  requests: number
  replies: number
  errors: number
  dropped: number
  flushed: number
  messages: Record<string, number>
}

/**
 * Probe host facts without attempting a mount. This is safe and rootless on
 * macOS and Linux; it reports the exact automatic preference and reasons.
 */
export declare function probeTransports(): Promise<JsAutoProbe>

export declare function rangeError(name: string, expected: string, value: number): RangeError

export declare function resolvePath(path: string): JsResolvedPath

export declare const S_IFBLK: number

export declare const S_IFCHR: number

export declare const S_IFDIR: number

export declare const S_IFIFO: number

export declare const S_IFLNK: number

export declare const S_IFMT: number

export declare const S_IFREG: number

export declare const S_IFSOCK: number

export declare const S_ISGID: number

export declare const S_IXGRP: number

export interface S3Credentials {
  accessKeyId: string
  secretAccessKey: string
}

export interface S3ServerOptions {
  bucket?: string
  host?: string
  port?: number
  credentials?: S3Credentials
  region?: string
  maxBodyBytes?: number
  maxXmlBytes?: number
  readChunkBytes?: number
}

export declare function splitPath(path: string): Array<string>

/**
 * Tear down every mount visible to the automatic facade and return failures
 * individually instead of rejecting the cleanup operation.
 */
export declare function unmountAll(): Promise<Array<JsMountFailure>>

export interface WebdavCredentials {
  username: string
  password: string
}

export interface WebdavServerOptions {
  host?: string
  port?: number
  credentials?: WebdavCredentials
  realm?: string
  readChunkBytes?: number
  maxXmlBytes?: number
  maxBodyBytes?: number
  drainTimeout?: number
  debug?: boolean
}

import type { FsError, FsErrorOptions } from "./types/root.js"
export type { ErrnoCode, FsError, FsErrorOptions } from "./types/root.js"
export { ERRNO_CODES, joinPath } from "./types/root.js"

import type { FsDriver } from "./types/driver.js"
export type { FsDriver, FileHandleLike, DirentLike } from "./types/driver.js"

export { createLoopback, resolveCapabilities } from "./types/harness.js"
export type { Loopback, ResolvedCapabilities } from "./types/harness.js"
